[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npm run build"

[deploy]
preDeployCommand = "npx prisma migrate deploy"
startCommand = "node ./app-server/server.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
